post_install() {
	echo -n "Updating font cache... "
	fc-cache -s
	mkfontscale /usr/share/fonts/TTF
	mkfontdir /usr/share/fonts/TTF
	echo "done"
}

post_upgrade() {
	echo -n "Updating font cache... "
	fc-cache -s
	mkfontscale /usr/share/fonts/TTF
	mkfontdir /usr/share/fonts/TTF
	echo "done"
}

post_remove() {
	echo -n "Updating font cache... "
	fc-cache -s
	mkfontscale /usr/share/fonts/TTF
	mkfontdir /usr/share/fonts/TTF
	echo "done"
}
